# Generated by Django 2.0.5 on 2018-05-04 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_usersnetworkconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersNetworkConfig',
            new_name='UserNetworkConfig',
        ),
    ]
